# https://code.visualstudio.com/api/working-with-extensions/continuous-integration
name: textmate-yara

on:
  pull_request:
    branches:
    - main
  push:
    branches-ignore:
    - 'releases/**/*'

jobs:
  unittests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        # only use the latest files
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    # npm "run" commands are defined in package.json the "scripts" section
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Lint tests
      run: npm run linttests
    - name: Build, test
      run: npm test
