# This workflow will publish the extension to the VSCode and OpenVSX marketplaces when a non-draft release has been published
# Steps taken from https://github.community/t/how-to-trigger-on-a-release-only-if-tag-name-matches-pattern/18514 (thank you brightran!)

on:
  release:
    types: [released]

name: publish
jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-tag.outputs.run_jobs }}
    steps:
      - name: Check Tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${GITHUB_REF} =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=run_jobs::true"
          else
            echo "::set-output name=run_jobs::false"
          fi

  deploy:
    needs: check_tag
    if: needs.check_tag.outputs.run_other_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build package
        run: |
          npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPENVSX_PUBLISHER }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCODE_PUBLISHER }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
