# This workflow will publish the extension to the VSCode and OpenVSX marketplaces when a non-draft release has been published

on:
  release:
    types: [released]
  push:
    paths:
    - '.github/workflows/publish.yml'

name: publish
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build package
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" =~ v[0-9]+.[0-9]+.[0-9]+ ]]
          then
            npm ci
          fi
      - name: Check condition
        if: success()
        run: 'echo ran anyway'
      # - name: Publish to Open VSX Registry
      #   if: success()
      #   uses: HaaLeo/publish-vscode-extension@v0
      #   with:
      #     pat: ${{ secrets.OPENVSX_PUBLISHER }}
      # - name: Publish to Visual Studio Marketplace
      #   if: success()
      #   uses: HaaLeo/publish-vscode-extension@v0
      #   with:
      #     pat: ${{ secrets.VSCODE_PUBLISHER }}
      #     registryUrl: https://marketplace.visualstudio.com
      #     extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
